apiVersion: v1
appVersion: "4.3.1"
description: Weblate is a free web-based translation management system.
name: weblate
version: 0.2.3
home: https://weblate.org/
icon: https://s.weblate.org/cdn/weblate.svg
maintainers:
  - name: tarioch
    email: patrick@ch.tario.org
