apiVersion: v1
appVersion: "4.0.2"
description: Weblate is a free web-based translation management system.
name: weblate
version: 0.1.4
home: https://weblate.org/
icon: https://weblate.org/static/img/logo.svg
maintainers:
- name: tarioch
  email: patrick@ch.tario.org
