apiVersion: v1
appVersion: "4.0.4"
description: Weblate is a free web-based translation management system.
name: weblate
version: 0.1.7
home: https://weblate.org/
icon: https://s.weblate.org/cdn/weblate-background.svg
maintainers:
- name: tarioch
  email: patrick@ch.tario.org
