{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "weblate.serviceAccountName" . }}
  labels:
{{ include "weblate.labels" . | indent 4 }}
{{- end -}}
